export const mockPets = [
  {
    id: '1',
    name: 'Buddy',
    species: 'Dog',
    breed: 'Golden Retriever',
    age: '2 years',
    gender: 'Male',
    location: 'Mumbai Animal Shelter',
    city: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=400',
    description: 'Friendly and energetic golden retriever looking for an active family.',
    vaccinated: true,
    neutered: true,
  },
  {
    id: '2',
    name: 'Luna',
    species: 'Cat',
    breed: 'Persian',
    age: '1 year',
    gender: 'Female',
    location: 'Paws & Whiskers NGO',
    city: 'Delhi',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    description: 'Sweet and calm Persian cat, perfect for apartment living.',
    vaccinated: true,
    neutered: false,
  },
  {
    id: '3',
    name: 'Max',
    species: 'Dog',
    breed: 'Labrador',
    age: '3 years',
    gender: 'Male',
    location: 'Care for Strays',
    city: 'Bangalore',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    description: 'Trained and well-behaved lab, great with kids.',
    vaccinated: true,
    neutered: true,
  },
];

export const mockMessages = [
  { id: '1', sender: 'shelter', text: 'Hello! Thank you for your interest in Buddy.', time: '10:30 AM' },
  { id: '2', sender: 'user', text: "Hi! I'd love to adopt Buddy. What's the process?", time: '10:32 AM' },
  { id: '3', sender: 'shelter', text: 'Great! We need to verify your living situation.', time: '10:35 AM' },
];